# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='app.Song'),
        ),
    ]
